<?php

return [

    'login'       => 'fas fa-sign-in-alt',
    'github'      => 'fab fa-github',
    'book'        => 'fa fa-book',
    'locale'      => 'fa fa-language',
    'certificate' => 'fa fa-certificate',
    'forum'       => 'fab fa-weixin',
    'logout'      => 'fas fa-sign-out-alt',
    'user'        => 'fa fa-user',
    'plane'       => 'fa fa-paper-plane',
    'check'       => 'fa fa-check',
    'clock'       => 'fa fa-clock-o',
    'tags'        => 'fa fa-tags',
    'comments'    => 'fa fa-comments',
    'reset'       => 'fa fa-refresh',
    'pencil'      => 'far fa-edit',
    'delete'      => 'far fa-trash-alt',
    'clip'        => 'fa fa-paperclip',
    'download'    => 'fas fa-cloud-download-alt',
    'dropdown'    => 'fa fa-chevron-down',
    'edit'        => 'fa fa-edit',
    'update'      => 'fa fa-paragraph',
    'reply'       => 'fa fa-reply',
    'preview'     => 'fa fa-code',
    'up'          => 'fa fa-chevron-up',
    'down'        => 'fa fa-chevron-down',
    'filter'      => 'fa fa-filter',
    'view_count'  => 'fa fa-eye',
    'sort'        => 'fa fa-sort',
    'desc'        => 'fa fa-sort-alpha-desc',
    'asc'         => 'fa fa-sort-alpha-asc',
    'new'         => 'fa fa-plus-circle',
    'notice'      => 'fa fa-bullhorn',
    'pin'         => 'fa fa-thumb-tack',
    'document'    => 'fa fa-file',
    'facebook'    => 'fab fa-facebook-square',
    'pick'        => 'far fa-thumbs-up',
    'change'      => 'fas fa-exchange-alt',
    'home'        => 'fas fa-home',
    'indent'      => 'fas fa-indent',
    'outdent'     => 'fas fa-outdent',
    'menubar'     => 'fas fa-bars',
    'arrow-left'  => 'fas fa-angle-left',
    'arrow-right' => 'fas fa-angle-right',
    'arrow-up'    => 'fas fa-angle-up',
    'arrow-down'  => 'fas fa-angle-down',
    'redo'        => 'fas fa-redo-alt',
    'setting'     => 'fas fa-cog',
    'qr_code'     => 'fas fa-qrcode',
];
